version: "3.9"

services:
  kinopoisk_parser:
    container_name: kinopoisk_parser
    build:
      context: .
      dockerfile: Dockerfile
      args:
        START_SCRIPT: ${START_SCRIPT}
    command: [sleep, infinity]
    depends_on:
      - postgres_kinopoisk_parser
    ports:
      - 8181:8181
#      - 5005:5005
    volumes:
      - ../:/java_rep
    environment:
      - DEBUG_IP=${DEBUG_IP}
      - DEBUG_PORT=${DEBUG_PORT}

  postgres_kinopoisk_parser:
    image: library/postgres:${POSTGRES_VERSION:-13}
    container_name: postgres_kinopoisk_parser
    environment:
      POSTGRES_DB: "${POSTGRES_DB:-db}"
      POSTGRES_USER: "${POSTGRES_USER:-root}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-root}"
    ports:
      - 54320:5432
    volumes:
      - ../local_data/database/data:/var/lib/postgresql/data

  redis_kinopoisk_parser:
    image: redis:latest
    container_name: redis_kinopoisk_parser
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ../local_data/redis_data:/data
    command: redis-server --appendonly yes

  redis_insight_kinopoisk_parser:
    image: redis/redisinsight:latest
    container_name: redis_insight_kinopoisk_parser
    restart: unless-stopped
    ports:
      - '5540:5540'
    depends_on:
      - redis_kinopoisk_parser
    volumes:
      - ../local_data/redis_insight_data:/db


networks:
  local_network:
    name: local_network
    ipam:
      config:
        -
          subnet: 172.20.0.0/24
          gateway: 172.20.0.1